# First R Lecture - The Analytics Edge
getwd()
WHO = read.csv("WHO.csv")
str(WHO)
summary(WHO)
who_europe= subset(WHO, Region == "Europe")
str(who_europe)
write.csv(who_europe,"WHO_Europe.csv")
ls()
rm(who_europe)
ls()
WHO$Under15
mean(WHO$Under15)
sd(WHO$Under15)
summary(WHO$Under15)
which.min(WHO$Under15)
which.max(WHO$Under15)
plot(WHO$GNI, WHO$fertilityrate)
Outliers = subset(WHO, GNI > 10000 & fertilityrate > 2.5)
nrow(Outliers)
Outliers[c("Country","GNI","FertilityRate")]
summary(WHO$Over60)
which.min(WHO$Over60)
WHO$Country[183]
summary(WHO$LiteracyRate)
which.max(WHO$LiteracyRate)
WHO$Country[44]
hist(WHO$CellularSubscribers)
boxplot(WHO$LifeExpectancy~ WHO$Region)
boxplot(WHO$LifeExpectancy~ WHO$Region, xlab="", ylab="Life Expectancy", main="Life expectancy by region")
table(WHO$Region)
tapply(WHO$Over60, WHO$Region, mean)
tapply(WHO$LiteracyRate, WHO$Region, min)
tapply(WHO$LiteracyRate, WHO$Region, min, na.rm=TRUE)
tapply(WHO$ChildMortality, WHO$Region, min, na.rm=TRUE)
tapply(WHO$ChildMortality, WHO$Region, mean, na.rm=TRUE)